"""AC-20: perf_1000 < 1.0 s and perf_150_x60 < 2.0 s, generated by
stress-corpus/src/perf_shapes.py (copied to fixtures/foreign/stress/src/). A test with a
large stored media member passes the cap (A-18)."""

import statistics
import subprocess
import sys
import time
import zipfile

import pytest

from keyline.lint import lint_path
from keyline.ooxml import package
from keyline.ooxml.package import ScanError
from tests.conftest import FOREIGN, GOLDEN

pytest.importorskip("pptx")

BUILDER = FOREIGN / "stress" / "src" / "perf_shapes.py"
BUDGET_S = {"perf_1000": 1.0, "perf_150_x60": 2.0}


@pytest.fixture(scope="module")
def perf_decks(tmp_path_factory):
    out = tmp_path_factory.mktemp("perf")
    subprocess.run(
        [sys.executable, str(BUILDER), str(out), *BUDGET_S],
        cwd=BUILDER.parent,
        check=True,
        capture_output=True,
    )
    return out


@pytest.mark.parametrize("name", list(BUDGET_S))
def test_perf_decks_within_budget(perf_decks, name):
    cmd = [sys.executable, "-m", "keyline", "lint", str(perf_decks / f"{name}.pptx"), "--json"]
    timings = []
    for _ in range(3):
        start = time.perf_counter()
        proc = subprocess.run(cmd, capture_output=True)
        timings.append(time.perf_counter() - start)
        assert proc.returncode == 2, proc.stderr.decode()
    print(f"{name} wall times: {', '.join(f'{t:.2f}s' for t in timings)}")
    assert statistics.median(timings) < BUDGET_S[name], timings


def _with_member(tmp_path, name, size):
    out = tmp_path / "deck.pptx"
    with zipfile.ZipFile(GOLDEN / "kpi-recipe.pptx") as zin, zipfile.ZipFile(out, "w") as zout:
        for info in zin.infolist():
            zout.writestr(info, zin.read(info.filename))
        zout.writestr(zipfile.ZipInfo(name), b"\0" * size, compress_type=zipfile.ZIP_STORED)
    return out


def test_large_stored_media_member_passes_the_cap(tmp_path, monkeypatch):
    monkeypatch.setattr(package, "MAX_TOTAL_UNCOMPRESSED", 1024 * 1024)  # 1 MB for the test
    deck = _with_member(tmp_path, "ppt/media/video1.mp4", 3 * 1024 * 1024)  # 3 MB of media
    assert lint_path(deck).exit_code == 2  # linted normally


def test_large_xml_part_still_hits_the_cap(tmp_path, monkeypatch):
    monkeypatch.setattr(package, "MAX_TOTAL_UNCOMPRESSED", 1024 * 1024)
    deck = _with_member(tmp_path, "ppt/customXml/item9.xml", 3 * 1024 * 1024)
    with pytest.raises(ScanError, match="uncompressed XML size"):
        lint_path(deck)
