"""Write the fit tables (spec 002 §6.4, B-8.11, B-21; task T-21).

    python tools/gen_fit_tables.py [OUT_DIR]

Dev only (fontTools, fontconfig). For each portable family and weight, fontconfig finds
the metric twin's TTF (the same substitution LibreOffice makes), and the table records:
- every codepoint of the twin's cmap with its advance width, in font units per em;
- the maximum advance (the estimate for a character the twin lacks);
- `line_pitch_em` = 1.2, with the LibreOffice versions that measured it (B-21, Q-44b);
- `hhea_line_em`, the twin's hhea line height (ascender - descender + line gap, over
  units per em, as an exact decimal), which table cells use when it exceeds 1.2 (B-22
  item 5);
- `descent_em`, the deepest a glyph reaches below the baseline, over Basic Latin, Latin-1,
  Latin Extended-A, the Vietnamese letters, digits and punctuation (from the glyph
  outlines), which the estimator keeps room for under a region's last line;
- the Vietnamese letters the twin lacks (audit 04);
- the source file's name, version, licence, copyright and SHA-256.

It also rewrites the generated block of NOTICE. Output is byte-stable: the same font
files give the same bytes.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from keyline.config import load as load_config  # noqa: E402
from keyline.fit import TABLES, VIETNAMESE, WEIGHTS, table_path  # noqa: E402

LINE_PITCH_EM = "1.2"  # B-21
MEASURED_ON = (
    "LibreOffice 24.2.7.2 420(Build:2) (audit 04)",
    "LibreOffice 26.8.0.3 680(Build:3) (T-20)",
)
NOTICE = ROOT / "NOTICE"
BEGIN = "--- font metric tables: generated by tools/gen_fit_tables.py ---"
END = "--- end of font metric tables ---"


def twin_file(family: str, weight: str) -> Path:
    style = "Bold" if weight == "bold" else "Regular"
    out = subprocess.run(
        ["fc-match", "-f", "%{file}", f"{family}:style={style}"], capture_output=True, text=True
    )
    return Path(out.stdout.strip())


def _name(font, name_id: int) -> str:
    return " ".join((font["name"].getDebugName(name_id) or "").split())


DESCENT_CHARS = [chr(c) for c in (*range(0x20, 0x7F), *range(0xA0, 0x180))]


def descent_em(font) -> str:
    """The deepest glyph descent below the baseline in em, exactly, over DESCENT_CHARS and
    the Vietnamese letters the twin has."""
    from fontTools.pens.boundsPen import BoundsPen

    cmap, glyphs = font.getBestCmap(), font.getGlyphSet()
    deepest = 0
    for ch in dict.fromkeys(DESCENT_CHARS + list(VIETNAMESE)):
        if ord(ch) in cmap:
            pen = BoundsPen(glyphs)
            glyphs[cmap[ord(ch)]].draw(pen)
            if pen.bounds is not None:
                deepest = min(deepest, pen.bounds[1])
    return str(Decimal(-deepest) / Decimal(font["head"].unitsPerEm))


def hhea_line_em(font) -> str:
    """The hhea line height in em, exactly: units per em is 1000 or a power of two."""
    hhea = font["hhea"]
    units = hhea.ascent - hhea.descent + hhea.lineGap
    return str(Decimal(units) / Decimal(font["head"].unitsPerEm))


def table(family: str, twin: str, weight: str) -> tuple[str, dict]:
    from fontTools.ttLib import TTFont

    path = twin_file(family, weight)
    font = TTFont(path)
    family_name = _name(font, 1)
    if family_name.casefold() != twin.casefold():
        sys.exit(f"stop: {family} {weight} resolves to {family_name}, not {twin}")
    cmap, hmtx = font.getBestCmap(), font["hmtx"]
    licence = _name(font, 13)
    source = {
        "file": path.name,
        "version": _name(font, 5),
        "licence": "OFL-1.1" if "SIL Open Font License" in licence else licence,
        "licence_url": _name(font, 14),
        "copyright": _name(font, 0),
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
    }
    head = {
        "schema": 1,
        "family": family,
        "twin": twin,
        "weight": weight,
        "units_per_em": font["head"].unitsPerEm,
        "max_advance": max(adv for adv, _lsb in hmtx.metrics.values()),
        "line_pitch_em": LINE_PITCH_EM,
        "hhea_line_em": hhea_line_em(font),
        "descent_em": descent_em(font),
        "measured_on": list(MEASURED_ON),
        "missing_vietnamese": "".join(c for c in VIETNAMESE if ord(c) not in cmap),
        "source": source,
    }
    pairs = [[cp, hmtx[glyph][0]] for cp, glyph in sorted(cmap.items())]
    text = json.dumps(head, ensure_ascii=False, indent=1)[:-2]
    text += ',\n "advances": ' + json.dumps(pairs, separators=(",", ":")) + "\n}\n"
    return text, source


def notice_block(sources: list[tuple[str, str, dict]]) -> str:
    lines = [BEGIN, "The fit tables in src/keyline/fit/tables/ hold advance widths derived from:"]
    seen = set()
    for _family, _twin, src in sources:
        if src["file"] in seen:
            continue
        seen.add(src["file"])
        lines.append(f"- {src['file']}, {src['version']}, {src['licence']} ({src['licence_url']})")
        lines.append(f"  {src['copyright']}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def build(out_dir: Path = TABLES, notice: Path | None = NOTICE) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written, sources = [], []
    for family, twin in load_config().portable_fonts:
        for weight in WEIGHTS:
            text, source = table(family, twin, weight)
            path = out_dir / table_path(twin, weight).name
            path.write_text(text, encoding="utf-8")
            written.append(path)
            sources.append((family, twin, source))
    if notice is not None:
        current = notice.read_text(encoding="utf-8")
        if BEGIN in current:
            current = current[: current.index(BEGIN)].rstrip("\n") + "\n"
        notice.write_text(current + "\n" + notice_block(sources), encoding="utf-8")
    return written


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else TABLES
    for p in build(out, NOTICE if out == TABLES else None):
        print(p)
