"""Write the fit tables (spec 002 §6.4, B-8.11, B-21; task T-21).

    python tools/gen_fit_tables.py [OUT_DIR]

Dev only (fontTools, fontconfig). For each portable family and weight, fontconfig finds
the metric twin's TTF (the same substitution LibreOffice makes), and the table records:
- every codepoint of the twin's cmap with its advance width, in font units per em;
- the maximum advance (the estimate for a character the twin lacks);
- `line_pitch_em` = 1.2, with the LibreOffice versions that measured it (B-21, Q-44b);
- `hhea_line_em`, the twin's hhea line height (ascender - descender + line gap, over
  units per em, as an exact decimal), which table cells use when it exceeds 1.2 (B-22
  item 5);
- over B-25's measured set (the characters the twin has and draws), from the glyph
  outlines: `descent_em`, the deepest a glyph reaches below the baseline, which the
  estimator keeps room for under a region's last line (Q-51); `top_em`, the highest a
  glyph reaches above it; and `left_em`, the furthest a glyph reaches left of its origin
  (B-25 items 2 and 3);
- `kern`, the positive kerning pairs inside the measured set (B-25 item 4), in font units:
  per pair, the largest positive x-advance adjustment of each GPOS pair lookup (format 1
  or 2, extension lookups included), summed over the lookups, and the legacy `kern` table's
  where it is larger; negative pairs are left out;
- the Vietnamese letters the twin lacks (audit 04);
- the source file's name, version, licence, copyright and SHA-256.

It also rewrites the generated block of NOTICE. Output is byte-stable: the same font
files give the same bytes.
"""

from __future__ import annotations

import hashlib
import json
import math
import subprocess
import sys
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from keyline.config import load as load_config  # noqa: E402
from keyline.fit import TABLES, VIETNAMESE, WEIGHTS, table_path  # noqa: E402
from keyline.fit.text import MEASURED, inked  # noqa: E402

MEASURED_SET = set(MEASURED)

LINE_PITCH_EM = "1.2"  # B-21
MEASURED_ON = (
    "LibreOffice 24.2.7.2 420(Build:2) (audit 04)",
    "LibreOffice 26.8.0.3 680(Build:3) (T-20)",
)
NOTICE = ROOT / "NOTICE"
BEGIN = "--- font metric tables: generated by tools/gen_fit_tables.py ---"
END = "--- end of font metric tables ---"


def twin_file(family: str, weight: str) -> Path:
    style = "Bold" if weight == "bold" else "Regular"
    out = subprocess.run(
        ["fc-match", "-f", "%{file}", f"{family}:style={style}"], capture_output=True, text=True
    )
    return Path(out.stdout.strip())


def _name(font, name_id: int) -> str:
    return " ".join((font["name"].getDebugName(name_id) or "").split())


def extents(font) -> dict[str, str]:
    """`descent_em`, `top_em` and `left_em` over the measured set: the deepest descent, the
    highest top and the furthest reach left of the origin of the glyphs the twin has and
    LibreOffice draws, in em, exactly (0 when none reaches)."""
    from fontTools.pens.boundsPen import BoundsPen

    cmap, glyphs, hmtx = font.getBestCmap(), font.getGlyphSet(), font["hmtx"]
    deepest = top = left = 0
    for ch in MEASURED:
        if ord(ch) not in cmap or not inked(ch):
            continue
        pen = BoundsPen(glyphs)
        glyphs[cmap[ord(ch)]].draw(pen)
        if pen.bounds is None:
            continue
        # outward to whole font units: outline extremes can fall between them
        deepest, top = min(deepest, math.floor(pen.bounds[1])), max(top, math.ceil(pen.bounds[3]))
        left = min(left, hmtx[cmap[ord(ch)]][1])
    upm = Decimal(font["head"].unitsPerEm)
    return {
        "descent_em": str(Decimal(-deepest) / upm),
        "top_em": str(Decimal(top) / upm),
        "left_em": str(Decimal(-left) / upm),
    }


def _pair_lookups(font):
    """Every GPOS pair-adjustment subtable, grouped by lookup."""
    if "GPOS" not in font:
        return []
    lookups = []
    for lookup in font["GPOS"].table.LookupList.Lookup:
        subtables = []
        for st in lookup.SubTable:
            if lookup.LookupType == 9:
                st = st.ExtSubTable
            if getattr(st, "LookupType", 2) == 2 and hasattr(st, "Coverage"):
                subtables.append(st)
        if subtables:
            lookups.append(subtables)
    return lookups


def _x_advance(value) -> int:
    return getattr(value, "XAdvance", 0) or 0 if value is not None else 0


def kern_pairs(font) -> list[list[int]]:
    """[[codepoint, codepoint, units], …] for the positive pairs whose characters are both
    in the measured set and in the twin, sorted."""
    cmap = font.getBestCmap()
    by_glyph: dict[str, list[int]] = {}
    for cp, glyph in cmap.items():
        if chr(cp) in MEASURED_SET:
            by_glyph.setdefault(glyph, []).append(cp)
    total: dict[tuple[str, str], int] = {}
    for subtables in _pair_lookups(font):
        best: dict[tuple[str, str], int] = {}
        for st in subtables:
            first = [g for g in st.Coverage.glyphs if g in by_glyph]
            if st.Format == 1:
                for g1 in first:
                    pairset = st.PairSet[st.Coverage.glyphs.index(g1)]
                    for rec in pairset.PairValueRecord:
                        if rec.SecondGlyph in by_glyph:
                            v = _x_advance(rec.Value1) + _x_advance(rec.Value2)
                            if v > best.get((g1, rec.SecondGlyph), 0):
                                best[g1, rec.SecondGlyph] = v
            elif st.Format == 2:
                class1, class2 = st.ClassDef1.classDefs, st.ClassDef2.classDefs
                seconds: dict[int, list[str]] = {}
                for g2 in by_glyph:
                    seconds.setdefault(class2.get(g2, 0), []).append(g2)
                for g1 in first:
                    row = st.Class1Record[class1.get(g1, 0)].Class2Record
                    for k2, rec in enumerate(row):
                        v = _x_advance(rec.Value1) + _x_advance(rec.Value2)
                        if v <= 0:
                            continue
                        for g2 in seconds.get(k2, ()):
                            if v > best.get((g1, g2), 0):
                                best[g1, g2] = v
        for pair, v in best.items():
            total[pair] = total.get(pair, 0) + v
    if "kern" in font:
        for sub in font["kern"].kernTables:
            for (g1, g2), v in getattr(sub, "kernTable", {}).items():
                if v > total.get((g1, g2), 0) and g1 in by_glyph and g2 in by_glyph:
                    total[g1, g2] = v
    return sorted(
        [c1, c2, v] for (g1, g2), v in total.items() for c1 in by_glyph[g1] for c2 in by_glyph[g2]
    )


def hhea_line_em(font) -> str:
    """The hhea line height in em, exactly: units per em is 1000 or a power of two."""
    hhea = font["hhea"]
    units = hhea.ascent - hhea.descent + hhea.lineGap
    return str(Decimal(units) / Decimal(font["head"].unitsPerEm))


def table(family: str, twin: str, weight: str) -> tuple[str, dict]:
    from fontTools.ttLib import TTFont

    path = twin_file(family, weight)
    font = TTFont(path)
    family_name = _name(font, 1)
    if family_name.casefold() != twin.casefold():
        sys.exit(f"stop: {family} {weight} resolves to {family_name}, not {twin}")
    cmap, hmtx = font.getBestCmap(), font["hmtx"]
    licence = _name(font, 13)
    source = {
        "file": path.name,
        "version": _name(font, 5),
        "licence": "OFL-1.1" if "SIL Open Font License" in licence else licence,
        "licence_url": _name(font, 14),
        "copyright": _name(font, 0),
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
    }
    head = {
        "schema": 1,
        "family": family,
        "twin": twin,
        "weight": weight,
        "units_per_em": font["head"].unitsPerEm,
        "max_advance": max(adv for adv, _lsb in hmtx.metrics.values()),
        "line_pitch_em": LINE_PITCH_EM,
        "hhea_line_em": hhea_line_em(font),
        **extents(font),
        "measured_on": list(MEASURED_ON),
        "missing_vietnamese": "".join(c for c in VIETNAMESE if ord(c) not in cmap),
        "source": source,
    }
    pairs = [[cp, hmtx[glyph][0]] for cp, glyph in sorted(cmap.items())]
    text = json.dumps(head, ensure_ascii=False, indent=1)[:-2]
    text += ',\n "advances": ' + json.dumps(pairs, separators=(",", ":"))
    text += ',\n "kern": ' + json.dumps(kern_pairs(font), separators=(",", ":")) + "\n}\n"
    return text, source


def notice_block(sources: list[tuple[str, str, dict]]) -> str:
    lines = [BEGIN, "The fit tables in src/keyline/fit/tables/ hold advance widths derived from:"]
    seen = set()
    for _family, _twin, src in sources:
        if src["file"] in seen:
            continue
        seen.add(src["file"])
        lines.append(f"- {src['file']}, {src['version']}, {src['licence']} ({src['licence_url']})")
        lines.append(f"  {src['copyright']}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def build(out_dir: Path = TABLES, notice: Path | None = NOTICE) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written, sources = [], []
    for family, twin in load_config().portable_fonts:
        for weight in WEIGHTS:
            text, source = table(family, twin, weight)
            path = out_dir / table_path(twin, weight).name
            path.write_text(text, encoding="utf-8")
            written.append(path)
            sources.append((family, twin, source))
    if notice is not None:
        current = notice.read_text(encoding="utf-8")
        if BEGIN in current:
            current = current[: current.index(BEGIN)].rstrip("\n") + "\n"
        notice.write_text(current + "\n" + notice_block(sources), encoding="utf-8")
    return written


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else TABLES
    for p in build(out, NOTICE if out == TABLES else None):
        print(p)
